protocol device {
    scan time 10;
}

protocol direct {
	interface "dummy*";
	ipv4;
	ipv6;
}

function kernel_export_filter() -> bool {
	if source !~ [RTS_BGP, RTS_STATIC] then return false;
	if is_default_route() then return true;
	if is_self_route() then return true;
	if is_downstream_route() then return true;
	return false;
}

filter kernel_export {
	if POP_KERNEL_EXPORT then {
		krt_prefsrc = POP_KERNEL_PREFSRC;
		accept;
	}
	kernel_export_filter();
}

protocol kernel {
    ipv6 { 
		import none; 
		export filter kernel_export;
	};
}
