protocol device {
    scan time 10;
}

protocol direct {
	interface "dummy*";
#	ipv4;
	ipv6;
}

function if_export_kernel() -> bool {
	if source !~ [RTS_BGP, RTS_STATIC] then return false;
	if is_default_route() then return true;
	if is_self_route() then return true;
	if is_downstream_route() then return true;
	return false;
}

function kernel_export_filter() -> bool {
	if !POP_KERNEL_EXPORT then return if_export_kernel();
	krt_prefsrc = POP_KERNEL_PREFSRC;
	return true;
}

protocol kernel {
    ipv6 { 
		import none; 
		export where kernel_export_filter();
	};
}
