protocol device {
    scan time 10;
}

protocol direct {
#	ipv4;
	ipv6;
}

function if_export_kernel {
	if source !~ [RTS_BGP, RTS_STATIC] then return false;
	if is_default_route() then return true;
	if is_self_route() then return true;
	if is_downstream_route() then return true;
	return false;
}

filter kernel_export {
	if POP_EXPORT_KERNEL = false {
		if_export_kernel();
	} else if POP_EXPORT_KERNEL = true {
		accept;
	}
	if_export_kernel();
}

protocol kernel {
    ipv6 { 
		import none; 
		export filter kernel_export;
	};
}
